export const MOCK_USER = {
  user_id: 'USR-001',
  erp_employee_id: 'EMP-9921',
  name: 'Nasir',
  department: 'Engineering',
  email: 'nasir@betopia.com',
  phone: '+8801700000000',
  role: 'Employee',
  salary_credit_balance: 15000,
  delivery_address: 'Betopia Headquarters, Floor 5, Desk 12',
};

export const CATEGORIES = [
  { id: 'cat_staples', name: 'Rice & Grains', icon: 'Box' },
  { id: 'cat_meat', name: 'Fish & Meat', icon: 'Beef' },
  { id: 'cat_veg', name: 'Vegetables', icon: 'Carrot' },
  { id: 'cat_dairy', name: 'Dairy & Eggs', icon: 'Milk' },
  { id: 'cat_spices', name: 'Spices & Oil', icon: 'Flame' },
  { id: 'cat_snacks', name: 'Snacks & Bakery', icon: 'Cookie' },
  { id: 'cat_beverages', name: 'Beverages', icon: 'Coffee' },
  { id: 'cat_hygiene', name: 'Hygiene & Care', icon: 'User' },
];

export const MOCK_PRODUCTS = [
  {
    product_id: 'P1',
    name: 'Aafi Olive Pickle (400 gm)',
    category: 'Spices & Oil',
    unit_price: 245,
    unit: 'pcs',
    available_units: ['1 pcs'],
    image_url: '/productImg/aafi-olive-pickle-400-gm.webp',
    stock_status: 'In stock',
    stock_qty: 45,
    discount_pct: 5
  },
  {
    product_id: 'P2',
    name: 'Ahmed White Vinegar (500 ml)',
    category: 'Spices & Oil',
    unit_price: 65,
    unit: 'pcs',
    available_units: ['1 pcs'],
    image_url: '/productImg/ahmed-white-vinegar-500-ml.webp',
    stock_status: 'In stock',
    stock_qty: 120,
    discount_pct: null
  },
  {
    product_id: 'P3',
    name: 'Bachun Oyster Sauce (350 ml)',
    category: 'Spices & Oil',
    unit_price: 380,
    unit: 'pcs',
    available_units: ['1 pcs'],
    image_url: '/productImg/bachun-oyster-sauce-350-ml.webp',
    stock_status: 'In stock',
    stock_qty: 30,
    discount_pct: 10
  },
  {
    product_id: 'P4',
    name: 'Barilla Pasta Sauce Basilico (400 gm)',
    category: 'Spices & Oil',
    unit_price: 450,
    unit: 'pcs',
    available_units: ['1 pcs'],
    image_url: '/productImg/barilla-pasta-sauce-jar-basilico-400-gm.webp',
    stock_status: 'In stock',
    stock_qty: 25,
    discount_pct: null
  },
  {
    product_id: 'P5',
    name: 'Broiler Chicken (Skin Off) 1kg',
    category: 'Fish & Meat',
    unit_price: 230,
    unit: 'kg',
    available_units: ['1 kg', '2 kg'],
    image_url: '/productImg/broiler-chicken-skin-off-50-gm-1-kg.webp',
    stock_status: 'In stock',
    stock_qty: 100,
    discount_pct: null
  },
  {
    product_id: 'P6',
    name: 'Chicken Whole Leg (Skin On) 1kg',
    category: 'Fish & Meat',
    unit_price: 260,
    unit: 'kg',
    available_units: ['1 kg', '2 kg'],
    image_url: '/productImg/broiler-whole-chicken-leg-skin-on-50-gm-1-kg.webp',
    stock_status: 'In stock',
    stock_qty: 80,
    discount_pct: 5
  },
  {
    product_id: 'P7',
    name: 'Chicken Eggs Layer (6 pcs)',
    category: 'Dairy & Eggs',
    unit_price: 75,
    unit: 'hali',
    available_units: ['1 hali'],
    image_url: '/productImg/chicken-eggs-layer-6-pcs.webp',
    stock_status: 'In stock',
    stock_qty: 200,
    discount_pct: null
  },
  {
    product_id: 'P8',
    name: 'Chicken Eggs Layer White (12 pcs)',
    category: 'Dairy & Eggs',
    unit_price: 145,
    unit: 'dozen',
    available_units: ['1 dozen'],
    image_url: '/productImg/chicken-eggs-layer-white-12-pcs.webp',
    stock_status: 'In stock',
    stock_qty: 150,
    discount_pct: 5
  },
  {
    product_id: 'P9',
    name: 'Fresh Poultry Chicken',
    category: 'Fish & Meat',
    unit_price: 210,
    unit: 'kg',
    available_units: ['1 kg', '2 kg'],
    image_url: '/productImg/chicken-poultry.webp',
    stock_status: 'In stock',
    stock_qty: 300,
    discount_pct: null
  },
  {
    product_id: 'P10',
    name: 'Chings Chilli Sauce (680 gm)',
    category: 'Spices & Oil',
    unit_price: 220,
    unit: 'pcs',
    available_units: ['1 pcs'],
    image_url: '/productImg/chings-chilli-sauce-680-gm.webp',
    stock_status: 'In stock',
    stock_qty: 60,
    discount_pct: null
  },
  {
    product_id: 'P11',
    name: 'Chinigura Rice Premium (1 kg)',
    category: 'Rice & Grains',
    unit_price: 160,
    unit: 'kg',
    available_units: ['1 kg', '2 kg', '5 kg'],
    image_url: '/productImg/chinigura-rice-premium-1-kg.webp',
    stock_status: 'In stock',
    stock_qty: 500,
    discount_pct: 10
  },
  {
    product_id: 'P12',
    name: 'Coriander Leaves (Dhonia Pata) 100g',
    category: 'Vegetables',
    unit_price: 40,
    unit: 'bundle',
    available_units: ['1 bundle'],
    image_url: '/productImg/coriander-leaves-dhonia-pata-10-gm-100-gm.webp',
    stock_status: 'In stock',
    stock_qty: 100,
    discount_pct: null
  },
  {
    product_id: 'P13',
    name: 'Traditional Dried Fish',
    category: 'Fish & Meat',
    unit_price: 850,
    unit: 'kg',
    available_units: ['500g', '1 kg'],
    image_url: '/productImg/dried-fish.webp',
    stock_status: 'In stock',
    stock_qty: 40,
    discount_pct: null
  },
  {
    product_id: 'P14',
    name: 'Farm Fresh Eggs',
    category: 'Dairy & Eggs',
    unit_price: 150,
    unit: 'dozen',
    available_units: ['1 dozen'],
    image_url: '/productImg/eggs.webp',
    stock_status: 'In stock',
    stock_qty: 400,
    discount_pct: null
  },
  {
    product_id: 'P15',
    name: 'Farm Fresh Ghee (200 gm)',
    category: 'Dairy & Eggs',
    unit_price: 320,
    unit: 'pcs',
    available_units: ['1 pcs'],
    image_url: '/productImg/farm-fresh-ghee-200-gm.webp',
    stock_status: 'In stock',
    stock_qty: 50,
    discount_pct: 5
  },
  {
    product_id: 'P16',
    name: 'Triphala Powder (100 gm)',
    category: 'Spices & Oil',
    unit_price: 110,
    unit: 'pcs',
    available_units: ['1 pcs'],
    image_url: '/productImg/farmers-gold-triphala-powder-100-gm.webp',
    stock_status: 'In stock',
    stock_qty: 100,
    discount_pct: null
  },
  {
    product_id: 'P17',
    name: 'Fresh Soyabean Oil (5 Ltr)',
    category: 'Spices & Oil',
    unit_price: 164, // Price per L
    unit: 'L',
    available_units: ['1 L', '2 L', '5 L'],
    image_url: '/productImg/fresh-fortified-soyabean-oil-5-ltr.webp',
    stock_status: 'In stock',
    stock_qty: 150,
    discount_pct: 2
  },
  {
    product_id: 'P18',
    name: 'Fresh Refined Sugar (1 kg)',
    category: 'Spices & Oil',
    unit_price: 135,
    unit: 'kg',
    available_units: ['1 kg', '2 kg'],
    image_url: '/productImg/fresh-refined-sugar-1-kg.webp',
    stock_status: 'In stock',
    stock_qty: 600,
    discount_pct: null
  },
  {
    product_id: 'P19',
    name: 'Premium Frozen Fish',
    category: 'Fish & Meat',
    unit_price: 450,
    unit: 'kg',
    available_units: ['1 kg', '2 kg'],
    image_url: '/productImg/frozen-fish.webp',
    stock_status: 'In stock',
    stock_qty: 70,
    discount_pct: null
  },
  {
    product_id: 'P20',
    name: 'Cinnamon Sticks (Daruchini) 100g',
    category: 'Spices & Oil',
    unit_price: 180,
    unit: 'pcs',
    available_units: ['1 pcs'],
    image_url: '/productImg/golden-grain-cinnamon-daruchini-100-gm.webp',
    stock_status: 'In stock',
    stock_qty: 100,
    discount_pct: null
  },
  {
    product_id: 'P21',
    name: 'Cumin Seeds (Jira) 100g',
    category: 'Spices & Oil',
    unit_price: 120,
    unit: 'pcs',
    available_units: ['1 pcs'],
    image_url: '/productImg/golden-grain-cumin-jira-100-gm.webp',
    stock_status: 'In stock',
    stock_qty: 200,
    discount_pct: null
  },
  {
    product_id: 'P22',
    name: 'Whole Baby Corn (425 gm)',
    category: 'Vegetables',
    unit_price: 195,
    unit: 'pcs',
    available_units: ['1 pcs'],
    image_url: '/productImg/king-bell-whole-baby-corn-tin-425-gm.webp',
    stock_status: 'In stock',
    stock_qty: 40,
    discount_pct: null
  },
  {
    product_id: 'P23',
    name: 'Special Lascha Semai (180 gm)',
    category: 'Snacks & Bakery',
    unit_price: 55,
    unit: 'pcs',
    available_units: ['1 pcs'],
    image_url: '/productImg/kolson-special-lascha-semai-180-gm.webp',
    stock_status: 'In stock',
    stock_qty: 300,
    discount_pct: null
  },
  {
    product_id: 'P24',
    name: 'Imported Orange (1 kg)',
    category: 'Vegetables',
    unit_price: 280,
    unit: 'kg',
    available_units: ['1 kg'],
    image_url: '/productImg/komola-orange-imported-50-gm-1-kg.webp',
    stock_status: 'In stock',
    stock_qty: 150,
    discount_pct: 10
  },
  {
    product_id: 'P25',
    name: 'Extra Virgin Olive Oil (500 ml)',
    category: 'Spices & Oil',
    unit_price: 950,
    unit: 'pcs',
    available_units: ['1 pcs'],
    image_url: '/productImg/la-espanola-extra-virgin-olive-oil-500-ml.webp',
    stock_status: 'In stock',
    stock_qty: 45,
    discount_pct: 5
  },
  {
    product_id: 'P26',
    name: 'Liquid UHT Milk (1 Ltr)',
    category: 'Dairy & Eggs',
    unit_price: 90,
    unit: 'L',
    available_units: ['1 L', '2 L'],
    image_url: '/productImg/liquid-uht-milk.webp',
    stock_status: 'In stock',
    stock_qty: 400,
    discount_pct: null
  },
  {
    product_id: 'P27',
    name: 'Premium Beef Meat',
    category: 'Fish & Meat',
    unit_price: 750,
    unit: 'kg',
    available_units: ['1 kg', '2 kg'],
    image_url: '/productImg/meat.webp',
    stock_status: 'In stock',
    stock_qty: 60,
    discount_pct: null,
    is_demand_based: true,
    demand_days: 2
  },
  {
    product_id: 'P28',
    name: 'Mug Dal (500 gm)',
    category: 'Rice & Grains',
    unit_price: 95,
    unit: 'pcs',
    available_units: ['1 pcs'],
    image_url: '/productImg/mug-dal-500-gm.webp',
    stock_status: 'In stock',
    stock_qty: 250,
    discount_pct: null
  },
  {
    product_id: 'P29',
    name: 'Nandos Peri-Peri Mild Sauce',
    category: 'Spices & Oil',
    unit_price: 450,
    unit: 'pcs',
    available_units: ['1 pcs'],
    image_url: '/productImg/nandos-peri-peri-mild-sauce-250-gm.webp',
    stock_status: 'In stock',
    stock_qty: 35,
    discount_pct: null
  },
  {
    product_id: 'P30',
    name: 'Assorted Table Sauces',
    category: 'Spices & Oil',
    unit_price: 180,
    unit: 'pcs',
    available_units: ['1 pcs'],
    image_url: '/productImg/other-table-sauces.webp',
    stock_status: 'In stock',
    stock_qty: 100,
    discount_pct: null
  },
  {
    product_id: 'P31',
    name: 'Premium Mixed Pickles',
    category: 'Spices & Oil',
    unit_price: 220,
    unit: 'pcs',
    available_units: ['1 pcs'],
    image_url: '/productImg/pickles.webp',
    stock_status: 'In stock',
    stock_qty: 80,
    discount_pct: 10
  },
  {
    product_id: 'P32',
    name: 'Potato Regular (1 kg)',
    category: 'Vegetables',
    unit_price: 55,
    unit: 'kg',
    available_units: ['1 kg', '5 kg'],
    image_url: '/productImg/potato-regular-50-gm-1-kg.webp',
    stock_status: 'In stock',
    stock_qty: 1000,
    discount_pct: null
  },
  {
    product_id: 'P33',
    name: 'Radhuni Chicken Masala (20 gm)',
    category: 'Spices & Oil',
    unit_price: 15,
    unit: 'pcs',
    available_units: ['1 pcs'],
    image_url: '/productImg/radhuni-chicken-masala-20-gm.webp',
    stock_status: 'In stock',
    stock_qty: 500,
    discount_pct: null
  },
  {
    product_id: 'P34',
    name: 'Radhuni Premium Ghee (200 gm)',
    category: 'Dairy & Eggs',
    unit_price: 350,
    unit: 'pcs',
    available_units: ['1 pcs'],
    image_url: '/productImg/radhuni-premium-ghee-200-gm.webp',
    stock_status: 'In stock',
    stock_qty: 60,
    discount_pct: null
  },
  {
    product_id: 'P35',
    name: 'Premium Miniket Rice',
    category: 'Rice & Grains',
    unit_price: 68,
    unit: 'kg',
    available_units: ['5 kg', '10 kg', '25 kg'],
    image_url: '/productImg/rice.webp',
    stock_status: 'In stock',
    stock_qty: 1000,
    discount_pct: 5
  },
  {
    product_id: 'P36',
    name: 'Ruchi Mango Pickle (400 gm)',
    category: 'Spices & Oil',
    unit_price: 190,
    unit: 'pcs',
    available_units: ['1 pcs'],
    image_url: '/productImg/ruchi-mango-pickle-400-gm.webp',
    stock_status: 'In stock',
    stock_qty: 120,
    discount_pct: null
  },
  {
    product_id: 'P37',
    name: 'Saad Hot Tomato Sauce (340 gm)',
    category: 'Spices & Oil',
    unit_price: 160,
    unit: 'pcs',
    available_units: ['1 pcs'],
    image_url: '/productImg/saad-hot-tomato-sauce-340-gm.webp',
    stock_status: 'In stock',
    stock_qty: 90,
    discount_pct: null
  },
  {
    product_id: 'P38',
    name: 'Shemai & Suji Pack',
    category: 'Snacks & Bakery',
    unit_price: 85,
    unit: 'pcs',
    available_units: ['1 pcs'],
    image_url: '/productImg/shemai-suji.webp',
    stock_status: 'In stock',
    stock_qty: 200,
    discount_pct: null
  },
  {
    product_id: 'P39',
    name: 'Shezan Tomato Ketchup (340 gm)',
    category: 'Spices & Oil',
    unit_price: 145,
    unit: 'pcs',
    available_units: ['1 pcs'],
    image_url: '/productImg/shezan-tomato-ketchup-340-gm.webp',
    stock_status: 'In stock',
    stock_qty: 110,
    discount_pct: null
  },
  {
    product_id: 'P40',
    name: 'Premium Mix Spices',
    category: 'Spices & Oil',
    unit_price: 320,
    unit: 'pcs',
    available_units: ['1 pcs'],
    image_url: '/productImg/spices.webp',
    stock_status: 'In stock',
    stock_qty: 150,
    discount_pct: null
  },
  {
    product_id: 'P41',
    name: 'Tiara Food Color Green (28 ml)',
    category: 'Spices & Oil',
    unit_price: 45,
    unit: 'pcs',
    available_units: ['1 pcs'],
    image_url: '/productImg/tiara-food-color-green-28-ml.webp',
    stock_status: 'In stock',
    stock_qty: 100,
    discount_pct: null
  },
  {
    product_id: 'P42',
    name: 'Watermelon Medium (1 pcs)',
    category: 'Vegetables',
    unit_price: 350,
    unit: 'pcs',
    available_units: ['1 pcs'],
    image_url: '/productImg/watermelon-medium-4-kg-tormuj-1-pcs.webp',
    stock_status: 'In stock',
    stock_qty: 40,
    discount_pct: null
  },
  {
    product_id: 'P43',
    name: 'Welcome Light Meat Tuna',
    category: 'Fish & Meat',
    unit_price: 280,
    unit: 'pcs',
    available_units: ['1 pcs'],
    image_url: '/productImg/welcome-light-meat-tuna-in-sunflower-oil-flake-170-gm.webp',
    stock_status: 'In stock',
    stock_qty: 55,
    discount_pct: null
  },
  {
    product_id: 'P44',
    name: 'Yogurt & Sweets Assorted',
    category: 'Dairy & Eggs',
    unit_price: 450,
    unit: 'kg',
    available_units: ['1 kg'],
    image_url: '/productImg/yogurt-sweets.webp',
    stock_status: 'In stock',
    stock_qty: 30,
    discount_pct: null
  }
];
